/**
 * 単語データ
 * CSVファイルの内容をJavaScript配列に変換したもの
 * ローカル環境でのCORS制限を回避するため、直接JSに埋め込み
 */
var WordData = [
  // ===== 自然・天気 =====
  { kanji: '桜', hiragana: 'さくら' },
  { kanji: '富士山', hiragana: 'ふじさん' },
  { kanji: '海', hiragana: 'うみ' },
  { kanji: '山', hiragana: 'やま' },
  { kanji: '川', hiragana: 'かわ' },
  { kanji: '空', hiragana: 'そら' },
  { kanji: '星', hiragana: 'ほし' },
  { kanji: '月', hiragana: 'つき' },
  { kanji: '太陽', hiragana: 'たいよう' },
  { kanji: '風', hiragana: 'かぜ' },
  { kanji: '雨', hiragana: 'あめ' },
  { kanji: '雪', hiragana: 'ゆき' },
  { kanji: '雲', hiragana: 'くも' },
  { kanji: '虹', hiragana: 'にじ' },
  { kanji: '紅葉', hiragana: 'もみじ' },
  { kanji: '花火', hiragana: 'はなび' },
  { kanji: '森', hiragana: 'もり' },
  { kanji: '湖', hiragana: 'みずうみ' },
  { kanji: '滝', hiragana: 'たき' },
  { kanji: '島', hiragana: 'しま' },
  { kanji: '草原', hiragana: 'そうげん' },
  { kanji: '砂浜', hiragana: 'すなはま' },
  { kanji: '夕焼け', hiragana: 'ゆうやけ' },
  { kanji: '朝焼け', hiragana: 'あさやけ' },
  { kanji: '台風', hiragana: 'たいふう' },
  { kanji: '稲妻', hiragana: 'いなずま' },
  { kanji: '霧', hiragana: 'きり' },
  { kanji: '露', hiragana: 'つゆ' },

  // ===== 動物 =====
  { kanji: '猫', hiragana: 'ねこ' },
  { kanji: '犬', hiragana: 'いぬ' },
  { kanji: '鳥', hiragana: 'とり' },
  { kanji: '象', hiragana: 'ぞう' },
  { kanji: '虎', hiragana: 'とら' },
  { kanji: '馬', hiragana: 'うま' },
  { kanji: '牛', hiragana: 'うし' },
  { kanji: '豚', hiragana: 'ぶた' },
  { kanji: '羊', hiragana: 'ひつじ' },
  { kanji: '兎', hiragana: 'うさぎ' },
  { kanji: '狐', hiragana: 'きつね' },
  { kanji: '狸', hiragana: 'たぬき' },
  { kanji: '熊', hiragana: 'くま' },
  { kanji: '鹿', hiragana: 'しか' },
  { kanji: '猿', hiragana: 'さる' },
  { kanji: '蛙', hiragana: 'かえる' },
  { kanji: '蝶', hiragana: 'ちょう' },
  { kanji: '蜂', hiragana: 'はち' },
  { kanji: '蟻', hiragana: 'あり' },
  { kanji: '亀', hiragana: 'かめ' },
  { kanji: '鯨', hiragana: 'くじら' },
  { kanji: 'イルカ', hiragana: 'いるか' },
  { kanji: 'ペンギン', hiragana: 'ぺんぎん' },
  { kanji: 'ライオン', hiragana: 'らいおん' },
  { kanji: 'キリン', hiragana: 'きりん' },

  // ===== 場所・建物 =====
  { kanji: '学校', hiragana: 'がっこう' },
  { kanji: '図書館', hiragana: 'としょかん' },
  { kanji: '公園', hiragana: 'こうえん' },
  { kanji: '病院', hiragana: 'びょういん' },
  { kanji: '駅', hiragana: 'えき' },
  { kanji: '空港', hiragana: 'くうこう' },
  { kanji: '温泉', hiragana: 'おんせん' },
  { kanji: '神社', hiragana: 'じんじゃ' },
  { kanji: '寺', hiragana: 'てら' },
  { kanji: '城', hiragana: 'しろ' },
  { kanji: '橋', hiragana: 'はし' },
  { kanji: '塔', hiragana: 'とう' },
  { kanji: '店', hiragana: 'みせ' },
  { kanji: '銀行', hiragana: 'ぎんこう' },
  { kanji: '郵便局', hiragana: 'ゆうびんきょく' },
  { kanji: '交番', hiragana: 'こうばん' },
  { kanji: '消防署', hiragana: 'しょうぼうしょ' },
  { kanji: '市役所', hiragana: 'しやくしょ' },
  { kanji: '体育館', hiragana: 'たいいくかん' },
  { kanji: '水族館', hiragana: 'すいぞくかん' },
  { kanji: '動物園', hiragana: 'どうぶつえん' },
  { kanji: '遊園地', hiragana: 'ゆうえんち' },
  { kanji: '映画館', hiragana: 'えいがかん' },
  { kanji: '美術館', hiragana: 'びじゅつかん' },
  { kanji: '博物館', hiragana: 'はくぶつかん' },

  // ===== 食べ物・飲み物 =====
  { kanji: '寿司', hiragana: 'すし' },
  { kanji: 'ご飯', hiragana: 'ごはん' },
  { kanji: 'パン', hiragana: 'ぱん' },
  { kanji: '味噌汁', hiragana: 'みそしる' },
  { kanji: 'ラーメン', hiragana: 'らーめん' },
  { kanji: 'うどん', hiragana: 'うどん' },
  { kanji: 'そば', hiragana: 'そば' },
  { kanji: 'カレー', hiragana: 'かれー' },
  { kanji: '天ぷら', hiragana: 'てんぷら' },
  { kanji: '焼き魚', hiragana: 'やきざかな' },
  { kanji: '卵焼き', hiragana: 'たまごやき' },
  { kanji: 'おにぎり', hiragana: 'おにぎり' },
  { kanji: '弁当', hiragana: 'べんとう' },
  { kanji: 'サラダ', hiragana: 'さらだ' },
  { kanji: 'スープ', hiragana: 'すーぷ' },
  { kanji: 'りんご', hiragana: 'りんご' },
  { kanji: 'みかん', hiragana: 'みかん' },
  { kanji: 'ぶどう', hiragana: 'ぶどう' },
  { kanji: 'いちご', hiragana: 'いちご' },
  { kanji: 'すいか', hiragana: 'すいか' },
  { kanji: 'お茶', hiragana: 'おちゃ' },
  { kanji: '牛乳', hiragana: 'ぎゅうにゅう' },
  { kanji: 'ジュース', hiragana: 'じゅーす' },
  { kanji: '水', hiragana: 'みず' },
  { kanji: 'アイス', hiragana: 'あいす' },
  { kanji: 'ケーキ', hiragana: 'けーき' },
  { kanji: 'チョコレート', hiragana: 'ちょこれーと' },

  // ===== 学校・文房具 =====
  { kanji: '鉛筆', hiragana: 'えんぴつ' },
  { kanji: '消しゴム', hiragana: 'けしごむ' },
  { kanji: 'ノート', hiragana: 'のーと' },
  { kanji: '教科書', hiragana: 'きょうかしょ' },
  { kanji: '定規', hiragana: 'じょうぎ' },
  { kanji: 'はさみ', hiragana: 'はさみ' },
  { kanji: 'のり', hiragana: 'のり' },
  { kanji: '筆箱', hiragana: 'ふでばこ' },
  { kanji: 'ランドセル', hiragana: 'らんどせる' },
  { kanji: '黒板', hiragana: 'こくばん' },
  { kanji: 'チョーク', hiragana: 'ちょーく' },
  { kanji: '机', hiragana: 'つくえ' },
  { kanji: '椅子', hiragana: 'いす' },
  { kanji: '時間割', hiragana: 'じかんわり' },
  { kanji: '宿題', hiragana: 'しゅくだい' },
  { kanji: 'テスト', hiragana: 'てすと' },
  { kanji: '給食', hiragana: 'きゅうしょく' },
  { kanji: '掃除', hiragana: 'そうじ' },
  { kanji: '休み時間', hiragana: 'やすみじかん' },
  { kanji: '運動会', hiragana: 'うんどうかい' },
  { kanji: '遠足', hiragana: 'えんそく' },
  { kanji: '修学旅行', hiragana: 'しゅうがくりょこう' },

  // ===== 乗り物 =====
  { kanji: '電車', hiragana: 'でんしゃ' },
  { kanji: '自動車', hiragana: 'じどうしゃ' },
  { kanji: 'バス', hiragana: 'ばす' },
  { kanji: '自転車', hiragana: 'じてんしゃ' },
  { kanji: '飛行機', hiragana: 'ひこうき' },
  { kanji: '船', hiragana: 'ふね' },
  { kanji: 'ヘリコプター', hiragana: 'へりこぷたー' },
  { kanji: '新幹線', hiragana: 'しんかんせん' },
  { kanji: '地下鉄', hiragana: 'ちかてつ' },
  { kanji: 'タクシー', hiragana: 'たくしー' },
  { kanji: '救急車', hiragana: 'きゅうきゅうしゃ' },
  { kanji: '消防車', hiragana: 'しょうぼうしゃ' },
  { kanji: 'パトカー', hiragana: 'ぱとかー' },

  // ===== 身体 =====
  { kanji: '頭', hiragana: 'あたま' },
  { kanji: '顔', hiragana: 'かお' },
  { kanji: '目', hiragana: 'め' },
  { kanji: '耳', hiragana: 'みみ' },
  { kanji: '鼻', hiragana: 'はな' },
  { kanji: '口', hiragana: 'くち' },
  { kanji: '手', hiragana: 'て' },
  { kanji: '足', hiragana: 'あし' },
  { kanji: '指', hiragana: 'ゆび' },
  { kanji: '心臓', hiragana: 'しんぞう' },

  // ===== 家族・人 =====
  { kanji: 'お父さん', hiragana: 'おとうさん' },
  { kanji: 'お母さん', hiragana: 'おかあさん' },
  { kanji: 'お兄さん', hiragana: 'おにいさん' },
  { kanji: 'お姉さん', hiragana: 'おねえさん' },
  { kanji: '弟', hiragana: 'おとうと' },
  { kanji: '妹', hiragana: 'いもうと' },
  { kanji: 'おじいさん', hiragana: 'おじいさん' },
  { kanji: 'おばあさん', hiragana: 'おばあさん' },
  { kanji: '先生', hiragana: 'せんせい' },
  { kanji: '友達', hiragana: 'ともだち' },

  // ===== 日本文化 =====
  { kanji: '侍', hiragana: 'さむらい' },
  { kanji: '忍者', hiragana: 'にんじゃ' },
  { kanji: '着物', hiragana: 'きもの' },
  { kanji: '浴衣', hiragana: 'ゆかた' },
  { kanji: '茶道', hiragana: 'さどう' },
  { kanji: '書道', hiragana: 'しょどう' },
  { kanji: '柔道', hiragana: 'じゅうどう' },
  { kanji: '剣道', hiragana: 'けんどう' },
  { kanji: '相撲', hiragana: 'すもう' },
  { kanji: '折り紙', hiragana: 'おりがみ' },

  // ===== スポーツ =====
  { kanji: '野球', hiragana: 'やきゅう' },
  { kanji: 'サッカー', hiragana: 'さっかー' },
  { kanji: 'バスケットボール', hiragana: 'ばすけっとぼーる' },
  { kanji: 'バレーボール', hiragana: 'ばれーぼーる' },
  { kanji: 'テニス', hiragana: 'てにす' },
  { kanji: '水泳', hiragana: 'すいえい' },
  { kanji: '体操', hiragana: 'たいそう' },
  { kanji: 'マラソン', hiragana: 'まらそん' },
  { kanji: 'スキー', hiragana: 'すきー' },
  { kanji: 'スケート', hiragana: 'すけーと' },

  // ===== 季節・行事 =====
  { kanji: '春', hiragana: 'はる' },
  { kanji: '夏', hiragana: 'なつ' },
  { kanji: '秋', hiragana: 'あき' },
  { kanji: '冬', hiragana: 'ふゆ' },
  { kanji: 'お正月', hiragana: 'おしょうがつ' },
  { kanji: '節分', hiragana: 'せつぶん' },
  { kanji: 'ひな祭り', hiragana: 'ひなまつり' },
  { kanji: '端午の節句', hiragana: 'たんごのせっく' },
  { kanji: '七夕', hiragana: 'たなばた' },
  { kanji: 'お盆', hiragana: 'おぼん' },
  { kanji: 'ハロウィン', hiragana: 'はろうぃん' },
  { kanji: 'クリスマス', hiragana: 'くりすます' },
  { kanji: '大晦日', hiragana: 'おおみそか' },
  { kanji: '誕生日', hiragana: 'たんじょうび' },
  { kanji: '入学式', hiragana: 'にゅうがくしき' },
  { kanji: '卒業式', hiragana: 'そつぎょうしき' },

  // ===== 短文 =====
  { kanji: 'おはようございます', hiragana: 'おはようございます' },
  { kanji: 'こんにちは', hiragana: 'こんにちは' },
  { kanji: 'こんばんは', hiragana: 'こんばんは' },
  { kanji: 'おやすみなさい', hiragana: 'おやすみなさい' },
  { kanji: 'ありがとう', hiragana: 'ありがとう' },
  { kanji: 'ごめんなさい', hiragana: 'ごめんなさい' },
  { kanji: 'いただきます', hiragana: 'いただきます' },
  { kanji: 'ごちそうさま', hiragana: 'ごちそうさま' },
  { kanji: 'いってきます', hiragana: 'いってきます' },
  { kanji: 'ただいま', hiragana: 'ただいま' },
  { kanji: 'おかえりなさい', hiragana: 'おかえりなさい' },
  { kanji: '頑張ります', hiragana: 'がんばります' },
  { kanji: 'よろしくお願いします', hiragana: 'よろしくおねがいします' },
  { kanji: '今日は晴れです', hiragana: 'きょうははれです' },
  { kanji: '明日も学校です', hiragana: 'あしたもがっこうです' },
  { kanji: '本を読みます', hiragana: 'ほんをよみます' },
  { kanji: '外で遊ぶ', hiragana: 'そとであそぶ' },
  { kanji: '勉強する', hiragana: 'べんきょうする' },
  { kanji: '早起きは三文の徳', hiragana: 'はやおきはさんもんのとく' },

  // ===== 数字を含む問題（約20問） =====
  { kanji: '1月', hiragana: '1がつ' },
  { kanji: '12月', hiragana: '12がつ' },
  { kanji: '1年生', hiragana: '1ねんせい' },
  { kanji: '6年生', hiragana: '6ねんせい' },
  { kanji: '1時間目', hiragana: '1じかんめ' },
  { kanji: '5時間目', hiragana: '5じかんめ' },
  { kanji: '100点', hiragana: '100てん' },
  { kanji: '3組', hiragana: '3くみ' },
  { kanji: '2階', hiragana: '2かい' },
  { kanji: '4月10日', hiragana: '4がつ10にち' },
  { kanji: '7時に起きる', hiragana: '7じにおきる' },
  { kanji: '8時に学校へ行く', hiragana: '8じにがっこうへいく' },
  { kanji: '3時のおやつ', hiragana: '3じのおやつ' },
  { kanji: '10分休み', hiragana: '10ぷんやすみ' },
  { kanji: '20分休み', hiragana: '20ぷんやすみ' },
  { kanji: '50メートル走', hiragana: '50めーとるそう' },
  { kanji: '25メートル泳ぐ', hiragana: '25めーとるおよぐ' },
  { kanji: '365日', hiragana: '365にち' },
  { kanji: '47都道府県', hiragana: '47とどうふけん' },
  { kanji: '1週間は7日', hiragana: '1しゅうかんは7にち' },

  // ===== 学校名 =====
  { kanji: '東京小学校', hiragana: 'とうきょうしょうがっこう' }
];